In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a=np.random.randint(1,20,10)
a

array([10,  4, 19, 16, 19, 17,  2, 16, 15,  6])

In [8]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
a=([5])
a*10

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [19]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a=np.random.rand(3,3)
a

array([[0.87142831, 0.80392619, 0.81414692],
       [0.55558894, 0.50902057, 0.49493317],
       [0.33624242, 0.49306922, 0.60226998]])

In [28]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.hstack(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])