In [1]:
# how to create a user define array

In [4]:
import numpy

In [6]:
import numpy as np

In [10]:
a=[]
size=int(input("Enter size:"))
for i in range(size):
    val=(input("Enter item:"))
    a.append(val)
b=np.array(a)
b

Enter size: 3
Enter item: sam
Enter item: 45
Enter item: raj


array(['sam', '45', 'raj'], dtype='<U3')

In [11]:
a=[]
size=int(input("Enter size:"))
for i in range(size):
    val=int(input("Enter item:"))
    a.append(val)
b=np.array(a)
b

Enter size: 5
Enter item: 6
Enter item: 8
Enter item: 9
Enter item: 4
Enter item: 5


array([6, 8, 9, 4, 5])

In [12]:
#how can we caheck shape and of an array


In [13]:
a=np.array([1,34,89,9900])

In [14]:
a

array([   1,   34,   89, 9900])

In [15]:
print("Total shape=",a.shape)
print("Total element=",a.size)

Total shape= (4,)
Total element= 4


In [16]:
a=[[1,2,3] ,[4,5,6], [7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#row_1=[1,2,3]
#row_2=[4,5,6]
#row_3=[7,8,9]

#col_1=[1,4,7]
#col_2=[2,5,8]
#col_3=[3,6,9]

In [20]:
print("Total shape=",b.shape)
print("Total element=",b.size)

Total shape= (3, 3)
Total element= 9


In [21]:
# images====> pixels(0-255) ====> opx black , 255px white ====> Normalize(0-1)px

# Intially weights ====? 0 , 1

# optimization ====> 0,1

# matrix ====> n(rows) = n(columns)

# symmatric matrix ====> n(rows) = n(columns)

# Asymtaarix matrix ====> n(rows) !=n(columns)

In [25]:
#predefine functions
#    (1) zeros() ====> it will create an array in which all the elements are 0

In [26]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [27]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#  (2) ones() ====> it will create an array in which all the elements are 1

In [31]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [32]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
type(a)

numpy.ndarray

In [34]:
a.shape

(2, 3)

In [35]:
a.size

6

In [36]:
# (3). eye() ====> in this function diagnolpostional are 1 and rest all are zero.

In [37]:
a=np.eye(4) # symmetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
a=np.eye(3,4) # asymatric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])