In [1]:
# how to create a user define array

In [4]:
import numpy

In [6]:
import numpy as np

In [10]:
a=[]
size=int(input("Enter size:"))
for i in range(size):
    val=(input("Enter item:"))
    a.append(val)
b=np.array(a)
b

Enter size: 3
Enter item: sam
Enter item: 45
Enter item: raj


array(['sam', '45', 'raj'], dtype='<U3')

In [11]:
a=[]
size=int(input("Enter size:"))
for i in range(size):
    val=int(input("Enter item:"))
    a.append(val)
b=np.array(a)
b

Enter size: 5
Enter item: 6
Enter item: 8
Enter item: 9
Enter item: 4
Enter item: 5


array([6, 8, 9, 4, 5])

In [12]:
#how can we caheck shape and of an array


In [13]:
a=np.array([1,34,89,9900])

In [14]:
a

array([   1,   34,   89, 9900])

In [15]:
print("Total shape=",a.shape)
print("Total element=",a.size)

Total shape= (4,)
Total element= 4


In [16]:
a=[[1,2,3] ,[4,5,6], [7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#row_1=[1,2,3]
#row_2=[4,5,6]
#row_3=[7,8,9]

#col_1=[1,4,7]
#col_2=[2,5,8]
#col_3=[3,6,9]

In [20]:
print("Total shape=",b.shape)
print("Total element=",b.size)

Total shape= (3, 3)
Total element= 9


In [21]:
# images====> pixels(0-255) ====> opx black , 255px white ====> Normalize(0-1)px

# Intially weights ====? 0 , 1

# optimization ====> 0,1

# matrix ====> n(rows) = n(columns)

# symmatric matrix ====> n(rows) = n(columns)

# Asymtaarix matrix ====> n(rows) !=n(columns)

In [25]:
#predefine functions
#    (1) zeros() ====> it will create an array in which all the elements are 0

In [26]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [27]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#  (2) ones() ====> it will create an array in which all the elements are 1

In [31]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [32]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
type(a)

numpy.ndarray

In [34]:
a.shape

(2, 3)

In [35]:
a.size

6

In [36]:
# (3). eye() ====> in this function diagnolpostional are 1 and rest all are zero.

In [37]:
a=np.eye(4) # symmetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
a=np.eye(3,4) # asymatric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [3]:
# (4). diag====> this function creats a two dimendional array with all the diagonal elements as the given value and rest are zero

In [4]:
import numpy as np
a=np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [5]:
# (5)randint==> this function is used to generate a random number between a given range
# syntax == randint(min_value,max_value,total-numbers)

In [7]:
import numpy as np
a=np.random.randint(1,10,3)
a

array([8, 9, 4])

In [8]:
# (6). rand()==> this function is used to geneate a random number between 0 to 1
# syntax == rand(numberofvalues)

In [10]:
import numpy as np
a=np.random.rand(5)
a

array([0.54622744, 0.16090257, 0.4347172 , 0.64583256, 0.2795605 ])

In [11]:
# (7) rnadn()==> this function is used to generate a random number from -3 to close 3. this may return positive or negative as well

In [12]:
# reshaping data

In [13]:
a=np.random.randint(1,50,12)
a

array([20, 36, 43, 42, 12,  5, 46, 48, 45, 15, 42, 36])

In [14]:
# n(rows) * n(columns) = n(total_elements(

In [15]:
a.shape

(12,)

In [16]:
a=a.reshape(2,6)
a

array([[20, 36, 43, 42, 12,  5],
       [46, 48, 45, 15, 42, 36]])

In [17]:
a=a.reshape(6,2)
a

array([[20, 36],
       [43, 42],
       [12,  5],
       [46, 48],
       [45, 15],
       [42, 36]])

In [18]:
a=a.reshape(3,4)
a

array([[20, 36, 43, 42],
       [12,  5, 46, 48],
       [45, 15, 42, 36]])

In [19]:
a=a.reshape(4,3)
a

array([[20, 36, 43],
       [42, 12,  5],
       [46, 48, 45],
       [15, 42, 36]])

In [20]:
# principal of -1

In [21]:
a=a.reshape(-1,4)
a

array([[20, 36, 43, 42],
       [12,  5, 46, 48],
       [45, 15, 42, 36]])

In [25]:
# seed function() ==> we know that randint function generates random numbers. everytime we run the program new set of random number is generated, so solve this problem we wikk use seed function 

In [26]:
np.random.seed(5)
a=np.random.randint(1,100,10)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [27]:
# view vs copy ==> when we silce a sub array from an array it may be done by two ways.

In [28]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [29]:
# copy

In [30]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [31]:
b

array([0, 0, 0])

In [32]:
# conditional selection

In [33]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [35]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [36]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [37]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
# operations on array

In [43]:
a=[1,2,3,4]
a*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [44]:
a=np.array([1,2,3,4])
a*2

array([2, 4, 6, 8])

In [45]:
a=np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [46]:
a+2

array([3, 4, 5, 6])

In [47]:
a**2

array([ 1,  4,  9, 16])

In [58]:
s=np.array([1,2,3,4]).reshape(2,2)
s

array([[1, 2],
       [3, 4]])

In [59]:
v=np.array([5,6,7,8]).reshape(2,2)
v

array([[5, 6],
       [7, 8]])

In [60]:
s+v

array([[ 6,  8],
       [10, 12]])

In [61]:
v-s

array([[4, 4],
       [4, 4]])

In [62]:
v/s

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [63]:
s*v

array([[ 5, 12],
       [21, 32]])

In [64]:
# some more important numpy functions

In [65]:
a=np.array([10,20,30,40,50])
np.min(a)

10

In [66]:
np.max(a)

50

In [68]:
np.argmin(a)

0

In [69]:
np.argmax(a)

4

In [70]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [71]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [72]:
# linspace() ==> this function returnsvalue between a given range and with a same gap between consicutive eements.

In [73]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [74]:
#np.unique(arr,return_index=true,retuen_counts=true)

In [77]:
a=np.array([10,20,30,40,10,20,50])
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [78]:
# horizontal and vertical stacking

In [79]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [80]:
b

array([5, 6, 7, 8])

In [81]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])